<template>
  <div class="flex w-full">
    <div
      class="
        flex
        items-center
        justify-center
        flex-grow
        basis-3/6
        h-[100px]
        bg-rose-200
      "
    >
      3/6
    </div>
    <div
      class="
        flex
        items-center
        justify-center
        flex-grow
        basis-2/6
        h-[100px]
        bg-yellow-200
      "
    >
      2/6
    </div>
    <div
      class="
        flex
        items-center
        justify-center
        flex-grow
        basis-1/6
        h-[100px]
        bg-green-200
      "
    >
      1/6
    </div>
  </div>
</template>
