<template>
  <div
    class="
      flex
      gap-[20px]
      items-center
      overflow-x-auto
      w-[500px]
      snap-x snap-mandatory
    "
  >
    <div
      class="
        flex-shrink-0 flex
        items-center
        justify-center
        w-[300px]
        h-[150px]
        bg-blue-200
        snap-start
      "
    >
      snap-start
    </div>
    <div
      class="
        flex-shrink-0 flex
        items-center
        justify-center
        w-[300px]
        h-[150px]
        bg-rose-200
        snap-center
      "
    >
      snap-center
    </div>
    <div
      class="
        flex-shrink-0 flex
        items-center
        justify-center
        w-[300px]
        h-[150px]
        bg-violet-200
        snap-center
      "
    >
      snap-center
    </div>
    <div
      class="
        flex-shrink-0 flex
        items-center
        justify-center
        w-[300px]
        h-[150px]
        bg-yellow-200
        snap-end
      "
    >
      snap-end
    </div>
  </div>
</template>
